import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { askForPermissionToReceiveNotifications } from "../push_message";

export default function Home() {
  // ! For push notification to work, the web page must be in background or minimized.
  // ! so, cant send from button click
  // ! use the below format to send from a backend or from postman
  const handleSend = () => {
    fetch("https://fcm.googleapis.com/fcm/send", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `key=${process.env.serverKey}`,
      },
      body: JSON.stringify({
        notification: {
          title: "Test Message",
          body: "Test 1",
          click_action: "http://localhost:3000/",
          icon: "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg",
        },
        to: "eF1T_mQXiDwgOJYzo-SJGV:APA91bEZAFX1fsRSvxe9E_Xixh6Gt3pexgX2q7wTpGTxYmKnrHT4qDHrYi4fGW5bWeKPAOq5ODlgh2AcGBqIK1qwpYw73MzuU8kBl1y0ggPKxe61JDacJsoXe2Y7gwEOTZrJ5BrlGSA1",
      }),
    });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a> Firebase web cloud messaging</a>
        </h1>

        <p className={styles.description}>Firebase version 9.6.1</p>

        <button onClick={askForPermissionToReceiveNotifications}>
          Click to receive notification
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
